### ISSUE TITLE
LambdaTest action is not working. 

### ISSUE THREAD

**Issue by basilmeer** [LambdaTest/LambdaTest-tunnel-action#30]
The Start tunnel is not working as intended. I have my secret keys in order as well 
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/18617547/189466208-371621a3-a14b-41c5-96c6-d1ec4d735b74.png">

```
- name: Start Tunnel
        uses: LambdaTest/LambdaTest-tunnel-action@v1
        id: tunnel
        with:
          user: ${{ secrets.LT_EMAIL }}
          accessKey: ${{ secrets.LT_ACCESS_KEY }}
          tunnelName: "my-tunnel-name"
```
here's my config as well 

```
require("dotenv").config();

exports.config = {
  user: process.env.LT_USERNAME,
  key: process.env.LT_ACCESS_KEY,

  updateJob: false,
  specs: ["./tests/specs/login_test.js"],
  exclude: [],

  commonCapabilities: {
    name: "my-lambdatest",
    build: "my-lambdatest",
    visual: false,
    video: true,
    console: false,
    network: false,
  },

  capabilities: [
    {
      browserName: "chrome",
      version: "latest",
      platform: "WIN10",
    },
    {
      browser: "firefox",
      version: "latest",
      platform: "WIN7",
    },
    {
      browser: "internet explorer",
      version: "latest",
      platform: "WIN10",
    },
    {
      browser: "MicrosoftEdge",
      version: "latest",
      platform: "WIN10",
    },
  ],

  logLevel: "info",
  coloredLogs: true,
  screenshotPath: "./errorShots/",
  baseUrl: "",
  waitforTimeout: 10000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  path: "/wd/hub",
  hostname: "hub.lambdatest.com",
  port: 80,

  framework: "mocha",
  mochaOpts: {
    ui: "bdd",
    timeout: 20000,
  },
};

// Code to support common capabilities
exports.config.capabilities.forEach(function (caps) {
  for (var i in exports.config.commonCapabilities)
    caps[i] = caps[i] || exports.config.commonCapabilities[i];
});

```
