### ISSUE TITLE
Action run fails if tunnelName contains space 

### ISSUE THREAD

**Issue by KengoTODA** [LambdaTest/LambdaTest-tunnel-action#8]
When I run the following step in action,

```yaml
    - name: Start Tunnel
      uses: LambdaTest/LambdaTest-tunnel-action@v1.0.0
      id: tunnel
      with:
        user: ${{ secrets.LT_MAIL }}
        accessKey: ${{ secrets.LT_ACCESS_KEY }}
        tunnelName: "GitHub Actions"
```

[The action run failed](https://github.com/KengoTODA/javadocky/runs/792452067#step:5:64) because the value of `--tunnelName` option was not wrapped:

> docker run --name=b28be0257d8dfed49fcc -d=true --net=host lambdatest/tunnel:latest --user *** --key *** --tunnelName GitHub Actions --controller github --infoAPIPort 34159

As a workaround, wrapping them manually like `tunnelName: "'GitHub Actions'"` can work.  
However, it's nice if this action supports tunnel name with spaces.
